version: "3.8"
services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: lewa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
